# --------------------------------------------------------------------------
# LibExiv2

SET (EXIV2_DESIRED_VERSION "0.18")
INCLUDE(${st-base_SOURCE_DIR}/cmakemodules/FindExiv2.cmake)

# Lib Exiv2
IF(NOT EXIV2_FOUND)
  MESSAGE(SEND_ERROR "Exiv2 library not found. Please set: EXIV2_INCLUDE_DIR : PATH and EXIV2_LIBRARIES : FILEPATH variables manually if you have exiv2 libs in a non standard location.")
ELSE(NOT EXIV2_FOUND)

	IF (EXIV2_DESIRED_VERSION_FOUND)
		SET (EXIV2_VERSIONGT_018_FOUND TRUE CACHE BOOL
			"Exiv2 versino GT 018.")
	ELSE (EXIV2_DESIRED_VERSION_FOUND)
		IF ( WIN32 )
			SET(EXIV2_VERSIONGT_018_FOUND FALSE CACHE BOOL
				"Exiv2 versino GT 018.")
		ELSE ( WIN32 )
			EXECUTE_PROCESS(COMMAND ${PKGCONFIG_EXECUTABLE} --atleast-version=0.18 exiv2 RESULT_VARIABLE _return_VALUE )
			if(_return_VALUE STREQUAL "0") #Found Exiv2 release >= 0.18
				set(EXIV2_VERSIONGT_018_FOUND TRUE)
			endif(_return_VALUE STREQUAL "0")
		ENDIF ( WIN32 )
	ENDIF (EXIV2_DESIRED_VERSION_FOUND)
ENDIF(NOT EXIV2_FOUND)

IF (EXIV2_VERSIONGT_018_FOUND)
	SET_PROPERTY(DIRECTORY APPEND PROPERTY COMPILE_DEFINITIONS "EXIV2_VERSIONGT_018_FOUND" )
	#SET( IMAGELIB_DEP_DEFINITIONS ${IMAGELIB_DEP_DEFINITIONS} "-D EXIV2_VERSIONGT_018_FOUND" )
ENDIF (EXIV2_VERSIONGT_018_FOUND)


