INCLUDE(${st_imagelib_SOURCE_DIR}/imagelib.cmake)
	
INCLUDE_DIRECTORIES( ${IMAGELIB_DEP_INCLUDE_DIR} )
ADD_DEFINITIONS( ${IMAGELIB_DEP_DEFINITIONS} )
	
INCLUDE_DIRECTORIES( ${st_imagelib_SOURCE_DIR} )
INCLUDE_DIRECTORIES( ${st_imagelib_BINARY_DIR} )
#SET( ST_IMAGELIB_LIBRARIES st_imagelib ${IMAGELIB_DEP_LIBRARIES})
SET( ST_IMAGELIB_LIBRARIES st_imagelib )

