INCLUDE_DIRECTORIES( ${st_SOURCE_DIR}/digikam )
INCLUDE_DIRECTORIES( ${st_digikam_BINARY_DIR} )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/themeengine )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/dimg )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/dimg/loaders )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/dimg/filters )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/dmetadata )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/curves )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/levels )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/whitebalance )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/jpegutils )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/threadimageio )
INCLUDE_DIRECTORIES( ${st_digikam_SOURCE_DIR}/lprof )

